// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDyoAW-PniSl_zDWlnApk2vWqOyBkqkhA',
    appId: '1:399015810118:web:38c10c09dc5d80244d2647',
    messagingSenderId: '399015810118',
    projectId: 'assessment5-fcc0d',
    authDomain: 'assessment5-fcc0d.firebaseapp.com',
    storageBucket: 'assessment5-fcc0d.appspot.com',
    measurementId: 'G-BP3TK48EB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIPHNi3HmNxUvVtnbAGmexC1YTMTbzsc',
    appId: '1:399015810118:android:55a1e1db7237dd514d2647',
    messagingSenderId: '399015810118',
    projectId: 'assessment5-fcc0d',
    storageBucket: 'assessment5-fcc0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB45D0HL4kHk8AwRI-ZCRTBS5x8yoNv3QA',
    appId: '1:399015810118:ios:df2175a8403e9e854d2647',
    messagingSenderId: '399015810118',
    projectId: 'assessment5-fcc0d',
    storageBucket: 'assessment5-fcc0d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB45D0HL4kHk8AwRI-ZCRTBS5x8yoNv3QA',
    appId: '1:399015810118:ios:2d35d3eaaf51fd144d2647',
    messagingSenderId: '399015810118',
    projectId: 'assessment5-fcc0d',
    storageBucket: 'assessment5-fcc0d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
